### ISSUE TITLE
Availability of GetRoomLists method

### ISSUE THREAD

**Issue by rohitverma007** [linkedin/pyexchange#43]
Is there a way to fetch all the room mailboxes / room lists. Something very similar to https://msdn.microsoft.com/en-us/library/office/dn643730(v=exchg.150).aspx#bk_GetRoomListewsma . Also, is there a way to manage the room mailboxes which is also supported by the EWS API.

**Comment by trustrachel** [comment]
Hi there. There isn't a way currently, but if you'd like to add one, I'd be happy to consider pull requests!
