### ISSUE TITLE
Library maintenance going forward?

### ISSUE THREAD

**Issue by seanson** [linkedin/pyexchange#70]
There are a few pull requests with additional functionality (in particular https://github.com/linkedin/pyexchange/pull/56 has some excellent RoomList additions that I've based my fork off of and have additional contributions for) but it appears the last update to this repository is two years ago.

Is there any plan to hand this or the entry in PyPi over to another entity?

**Comment by stemid** [comment]
I think it's time to fork this project for good. @seanson where is this fork you speak of? Right now it seems to me that @pusnik has the most attractive fork I would like to keep working with.

**Comment by seanson** [comment]
@stemid the fork is linked in the above issue #56 but yes it is the @pusnik fork that I feel has the most value. Is there someone we can reach out to LinkedIn to ask about ownership?

**Comment by Achimh3011** [comment]
If you want a non-personal place to put such a fork, I'd like to offer [pycontribs](https://github.com/pycontribs), which is an organization exactly about saving abandoned projects.

**Comment by pusnik** [comment]
I totally agree, we need to fork the repo and continue with the development. We are intensively using this library in production so it would be great to keep this repo alive.

**Comment by seanson** [comment]
It's been a while and I'm just following up! Since I've last addressed this, there has been significant work on UberGrape's fork (https://github.com/ubergrape/pyexchange) and I'd probably put that as the best bet for a new starting place. I've fired off an email to @koniiik to ask him if he agrees, though I am still at a loss of how to contact LinkedIn Engineering (I've given them a shout on Twitter today, maybe that'll do it?).

I've also sent an email to PyContribs (https://github.com/pycontribs) asking if they'd like to re-home this library under their group as it's the only real place I can find for abandoned python projects!

If anyone else has suggestions I'd be glad to hear them.

**Comment by seanson** [comment]
I've gotten a response back from UberGrape who are glad to offer their fork as a place to centralise development for the time being. I believe the current pypi policy is not to allow reclaiming of abandoned names but can't find this in writing anywhere so a solution will be needed for that as well, either further attempts to contact LinkedIn or picking a new package name.
